# Generated by Django 3.0.7 on 2020-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200713_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='up_or_down',
            field=models.CharField(choices=[('O', 'one'), ('TW', 'two'), ('TH', 'three'), ('FO', 'four'), ('FI', 'five')], max_length=2),
        ),
    ]
