# Generated by Django 3.0.7 on 2020-07-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200713_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='up_or_down',
            new_name='rating',
        ),
    ]
