# Generated by Django 3.0.7 on 2020-07-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20200713_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', related_query_name='votes', to='Shop.Vote_Comment'),
        ),
    ]
